#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>

#
#Add custom config directory for Prezto
#

fpath=($HOME/.zsh/prezto-themes $fpath)

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
for config_file ($HOME/.zsh/zsh.d/*.zsh) source $config_file

#source $HOME/.LS_COLORS/ls_colors.zsh


